use super::*;

/// Catch-all property-data adapter that uses Godot's reflection (`get_indexed` /
/// `set_indexed`) to read & write the property at `path` on `owner`.
///
/// This is the type used by [`SpireTween::<LerpPropertyData<Variant>>::new_custom`]
/// and serves as the fallback when no specialized adapter matches a given property
/// path. Because it uses reflection, it works on *any* property regardless of type
/// — at the cost of one variant conversion per tick.
///
/// For built-in properties (e.g. `Node2D::position`, `CanvasItem::modulate`)
/// prefer the specialized adapters generated by `gdscript_bindgen`, which call the
/// native getter/setter directly without going through `Variant`. For one-off custom
/// properties exposed via callables, prefer [`PropertyDataViaCallable`].
#[derive(Debug, Clone)]
pub struct PropertyDataCustom {
    /// Path of the property (e.g. `"position:x"` for sub-properties via colon syntax).
    pub path:  NodePath,
    /// The object the property lives on. Used for both `get_indexed`/`set_indexed`
    /// and for liveness/pause-mode checks.
    pub owner: ObjectOrNode,
}

impl PropertyType for Variant {
    type Data = PropertyDataCustom;
}

impl TyToPropertyTween for Variant {
    type GdTween = SpireProperty;
}

impl<T: Default + FromGodot + ToGodot> IProperty<T> for PropertyDataCustom {
    fn get_property_value(&self) -> T {
        match &self.owner {
            ObjectOrNode::Object(obj) => obj
                .get_indexed(&self.path)
                .try_to_relaxed::<T>()
                .map_err(|err| {
                    godot_warn!("Failed to convert property '{}' value to target type. Error: {err:?}", self.path);
                })
                .log_if_err()
                .unwrap_or_default(),
            ObjectOrNode::Node(obj) => obj
                .get_indexed(&self.path)
                .try_to_relaxed::<T>()
                .map_err(|err| {
                    godot_warn!("Failed to convert property '{}' value to target type. Error: {err:?}", self.path);
                })
                .log_if_err()
                .unwrap_or_default(),
        }
    }

    fn set_property_value(&mut self, value: T) {
        match &mut self.owner {
            ObjectOrNode::Object(obj) => obj.set_indexed(&self.path, &value.to_variant()),
            ObjectOrNode::Node(obj) => obj.set_indexed(&self.path, &value.to_variant()),
        }
    }
}

impl IPropertyData for PropertyDataCustom {
    type Target = Object;

    fn get_property_path(&self) -> NodePath { self.path.clone() }
    fn get_owner(&self) -> Option<&ObjectOrNode> { Some(&self.owner) }
}

impl IGeneralPropertyData for PropertyDataCustom {
    fn from_path_and_owner(_path_str: &str, path: NodePath, owner: Gd<Object>) -> Self {
        Self {
            path,
            owner: ObjectOrNode::from_unchecked_object(owner),
        }
    }
}
